### ISSUE TITLE
paynl3.tpl is still missing or reffered to wrong location

### ISSUE THREAD

**Issue by CriZzZz** [paynl/opencart2-plugin#1]
In the latest version this is still happening. I placed a folder in catalog/view/theme called payment and inside the paynl3.tpl and it works. So in my case it is not solved yet.

**Comment by andypieters** [comment]
Some themes alter opencart's view function in a way that makes it impossible for me to know what path is should supply to the view function.
I've implemented loading the view in the same way the default opencart payment methods are using the view function
